language: objective-c
before_install:
  - brew update
  - brew uninstall xctool
  - brew install xctool
  - export LANG=en_US.UTF-8
  - gem i cocoapods --no-ri --no-rdoc -v "0.33.0"
xcode_workspace: TSMiniWebBrowser.xcworkspace
xcode_scheme: TSMiniWebBrowserDemo
xcode_sdk: iphonesimulator

